python train.py \
    --model_name google/gemma-2-2b-it \
    --layers 20 \
    --dataset_name monology/pile-uncopyrighted \
    --seq_len 128 \
    --batch_size 16 \
    --loss_threshold 0.0003 \
    --k 40 \
    --total_sequences 100000 \
    --crop_dict_size 16384 \
    --device cuda \
    --use_huggingface \
    --offload_to_disk \
    --offload_folder ./offload_weights